### ISSUE TITLE
Idea - Home->Die neuste Utility->Ref link to the util page + expand option for recent additions

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#100]
Option for expanding the "Die neuste utility" window.
Newly added util pushes the recently added out of view. In sessions with more additions, if you want to look e.g. at your 6th last entry, you'd have to click through the whole utility tab. + Way more convenient to just have your mate tell you "just added a smoke", go on the page and end on the right util piece page within 1 click

**Comment by jCodin** [comment]
fixed
