### ISSUE TITLE
Demo Viewer/Analyse broken

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#104]
When selecting a demo to view, following error occurs and you can't switch back into Home or any other Tab
![error](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/83806455/e1829592-0a7a-4b88-849c-20d3473a152c)

**Comment by jCodin** [comment]
fixed, it happend when you have clicked on a demo, that has been uploaded right before
