### ISSUE TITLE
Idea - Appointment series for officials in team calendar

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#108]
When a league has fixed match days each week, adding appointments in a series of weekly repeating games could be helpful.
Like giving a time window (start- & enddate) and then having a checklist of weekdays. And when you check a weekday, you can select at which time the game starts. After confirming, the whole series of appointments in that timespan is added to the calendar. Just make sure that it also can be deleted as a whole series, so it goes both ways.

**Comment by jCodin** [comment]
done
