### ISSUE TITLE
Utility: Learning mode

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#109]
Button inside Utility Tab "Learning mode":
Geht für die ausgewählte map random Utility durch

Beispiel für 
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/02c5d623-d16e-4842-b3de-d874679b9830)

-> Popup Smoke von T Spawn für HenryG 1

Chrome Erweiterung um Lösungsvideo anzuzeigen und weiter zu klicken

**Comment by GunnarLuebbermann** [comment]
Player an Util linken. Nicht jede Util ist für jeden notwendig

**Comment by jCodin** [comment]
donneee
