### ISSUE TITLE
Calendar: Do not show old match days/training days

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#11]
Should only show match day/training days for today + future

![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/0abb0c5c-acba-4613-a6b6-d594a3597cd0)

**Comment by jCodin** [comment]
fixed, would it be good to have an list with all old training sessions?

**Comment by GunnarLuebbermann** [comment]
imo not needed
