### ISSUE TITLE
Bug - HTML encoding not translated in Focus Mode pop-up

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#113]
![bug](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/83806455/c4fee45a-5fc4-43cb-bde3-798a69d9720c)
Edit:
An idea would be to think about making HTML encoding a valid option in the whole stratbook and cheatsheet contents, so there's no problem in streaming those back and forth.

**Comment by jCodin** [comment]
fixed
