### ISSUE TITLE
Idea - Possibility to highlight Utility as "default" or "individual"

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#114]
What I mean is being able to tag a piece of utility in the utility tab. 
Tags could for example be "default" and "individual", so players browsing the utility tab can see, what the default lineups are that everyone should be able to throw and so on. If the tags could make the util piece appear in a different color on the map, it would also mean an easier overview.

**Comment by jCodin** [comment]
done - colors are still missing, will be implemented later, when i get new map-files from lenny.

If you switch to the table-view of the utility, you can easily filter for individual or standard util (or linked players)
