### ISSUE TITLE
Bug - Change in link text is not accepted after clicking "Update"

### ISSUE THREAD

**Issue by Ferekdoch** [GunnarLuebbermann/my-csmanager-issues#115]
Editing in the stratbook, I found a typo and wanted to correct it, but the change is not accepted.
Before:
![bug1](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/83806455/efb04c50-ee24-40a2-9a23-244f362ec100)
Trying to correct:
![bug2](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/83806455/2f9376c5-fffe-4903-b8c1-3f9df95c19c4)
After:
![bug3](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/83806455/ab242433-bd4c-4d28-8d40-033541b30ed0)

**Comment by jCodin** [comment]
lol, i didn´t even know that this is possible. 
I´ll remove the option to edit a link. If you have a typo in one of your util, u need to correct it in the utility-page.

**Comment by jCodin** [comment]
fixed
