### ISSUE TITLE
Schriftart/Größe auf default setzen

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#129]
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/a0e6d7d5-15d5-4109-9d2a-2827e9121828)

Füge hier sowas hinzu:
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/9aaa0922-2e00-4ed6-b80c-2d78da4ed513)

**Comment by jCodin** [comment]
sollte jetzt immer einheitlich in der zukunft sein.

Formate werden nicht übernommen und es wird einfach plain text übernommen
