### ISSUE TITLE
Util in Strat: Zeige nur die Util der Map an

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#130]
Bei einer Ancient Strat kann ich Util von z.B. nuke auswählen:
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/7c6e4cf7-dbfa-4e07-9f8b-fea3bf148c63)

**Comment by jCodin** [comment]
fxied
