### ISSUE TITLE
Incorrect calculation for Util

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#22]
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/2e9a749e-bdc4-42f3-96c5-10d79b0ffd3a)

Kit: 400$
Flash 200$
Flash 200$

should be 800$ total.

**Comment by GunnarLuebbermann** [comment]
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/0f4d9e21-21ca-43f6-8979-b203d8051447)

**Comment by jCodin** [comment]
fixxxxed
