### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#3]
Empty User page

https://www.my-csmanager.com/Benutzer/Profil

![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/01d8b4f0-9e80-4c7e-9dbe-51a10c981769)

**Comment by GunnarLuebbermann** [comment]
Remove if there is no reason for a profile page

**Comment by jCodin** [comment]
Irgendwas schönes kann man da doch sicher anzeigen 🗡️
