### ISSUE TITLE
"Bemerkungen" are only shown in CheatSheet but not in Playbooks

### ISSUE THREAD

**Issue by 1VASAN** [GunnarLuebbermann/my-csmanager-issues#52]
"Bemerkungen" only shown in Cheatsheet. It should also be shown in Playbooks but its only visible when editing a certain player role. 

![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/148000109/1509ae11-a7e9-43cc-b7a6-669d46658ff1)

**Comment by jCodin** [comment]
fixed
