### ISSUE TITLE
Youtube Videos broken

### ISSUE THREAD

**Issue by 1VASAN** [GunnarLuebbermann/my-csmanager-issues#63]
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/148000109/8a36d305-6c5d-4e38-a7f6-35b8bc0b8869)

**Comment by GunnarLuebbermann** [comment]
yerp, can confirm. Also timestamp in videos does no work ie: https://www.youtube.com/watch?v=r270195a-PQ&t=60s

**Comment by jCodin** [comment]
fixed
