### ISSUE TITLE
Add function in 2D Analyser 

### ISSUE THREAD

**Issue by 1VASAN** [GunnarLuebbermann/my-csmanager-issues#74]
Add function to the 2d analyser to be able to skip through a round simply by pressing at a certain point in the "time bar". Right now you have to click, hold and move the red "time indicator", so you can skip through the round.

This would improve performance while reviewing demos. Function already exists when you click on util pieces which were thrown.

**Comment by jCodin** [comment]
fixed, thanks for improving the csm 👍
