### ISSUE TITLE
Strange double datepicker

### ISSUE THREAD

**Issue by GunnarLuebbermann** [GunnarLuebbermann/my-csmanager-issues#8]
Datepicker should not appear 2x. Currently, start date is selected on the left and end date on the right. One date picker for start/end should be enough and is common (?).

![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/12738046/73148bac-7cb9-48b1-94a5-268505eba98f)

**Comment by jCodin** [comment]
unfortunate, theres no api to to so.. maybe syncfusion will add this in future
