### ISSUE TITLE
Recorder lags for certain people

### ISSUE THREAD

**Issue by 1VASAN** [GunnarLuebbermann/my-csmanager-issues#93]
- Recording from 13th of December 2023 Vertigo
- Recording is fine for Lenny and encoree
- Lags for Trashhero, toan and VSN
- Video quality and frames should be improved even though that means bigger files
- Mobile / Tablet compatibility should be improved in the far future
- Replay the recording doesn work properly there

**Comment by jCodin** [comment]
-quality is better now,
-lags should be removes -> depends on own internet conneciton
-if one video is not loaded, all others are set to pause -> if you start a video to play, the application checks all other videos for their loaded data and prevents "play" if one is not loaded.
