### ISSUE TITLE
HE Icon is not shown in Fnatic (Inferno T Side Strategy)

### ISSUE THREAD

**Issue by 1VASAN** [GunnarLuebbermann/my-csmanager-issues#94]
I tried to add the HE again but Icon is still not showing
Money for HE although is included in total cost

![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/148000109/965f7811-1347-458d-b3f5-6af87af3fe78)

**Comment by jCodin** [comment]
![image](https://github.com/GunnarLuebbermann/my-csmanager-issues/assets/58491327/f7c67f72-3942-4133-ae46-08265d63f482)

is it still missing?
